export interface Destination {
  id: string;
  cityName: string;
  countryName: string;
  image: string;
  isPopular?: boolean;
  secondCityName?: string;
  secondCountryName?: string;
  category: "popular" | "cities" | "countries" | "regions" | "airports";
}

export const allDestinations: Destination[] = [
  // Popular Routes
  {
    id: "1",
    cityName: "Istanbul",
    countryName: "Turkey",
    image: "https://picsum.photos/300/200?random=21",
    isPopular: true,
    category: "popular",
    secondCityName: "Bursa",
    secondCountryName: "Turkey",
  },
  {
    id: "2",
    cityName: "Washington, D.C.",
    countryName: "USA",
    image: "https://picsum.photos/300/200?random=22",
    isPopular: true,
    category: "popular",
    secondCityName: "Alexandria",
    secondCountryName: "USA",
  },
  {
    id: "3",
    cityName: "New York",
    countryName: "USA",
    image: "https://picsum.photos/300/200?random=23",
    isPopular: true,
    category: "popular",
    secondCityName: "Newark",
    secondCountryName: "USA",
  },
  {
    id: "4",
    cityName: "London",
    countryName: "UK",
    image: "https://picsum.photos/300/200?random=24",
    isPopular: true,
    category: "popular",
    secondCityName: "Manchester",
    secondCountryName: "UK",
  },
  {
    id: "5",
    cityName: "Paris",
    countryName: "France",
    image: "https://picsum.photos/300/200?random=25",
    isPopular: true,
    category: "popular",
    secondCityName: "Versailles",
    secondCountryName: "France",
  },
  {
    id: "6",
    cityName: "Tokyo",
    countryName: "Japan",
    image: "https://picsum.photos/300/200?random=26",
    isPopular: true,
    category: "popular",
    secondCityName: "Osaka",
    secondCountryName: "Japan",
  },
  {
    id: "7",
    cityName: "Dubai",
    countryName: "UAE",
    image: "https://picsum.photos/300/200?random=27",
    isPopular: true,
    category: "popular",
    secondCityName: "Sharjah",
    secondCountryName: "UAE",
  },
  {
    id: "8",
    cityName: "Los Angeles",
    countryName: "USA",
    image: "https://picsum.photos/300/200?random=28",
    isPopular: true,
    category: "popular",
    secondCityName: "San Diego",
    secondCountryName: "USA",
  },
  {
    id: "9",
    cityName: "Sydney",
    countryName: "Australia",
    image: "https://picsum.photos/300/200?random=29",
    isPopular: true,
    category: "popular",
    secondCityName: "Melbourne",
    secondCountryName: "Australia",
  },
  // Cities
  {
    id: "10",
    cityName: "Mumbai",
    countryName: "India",
    image: "https://picsum.photos/300/200?random=30",
    category: "cities",
  },
  {
    id: "11",
    cityName: "Bangkok",
    countryName: "Thailand",
    image: "https://picsum.photos/300/200?random=31",
    category: "cities",
  },
  {
    id: "12",
    cityName: "Singapore",
    countryName: "Singapore",
    image: "https://picsum.photos/300/200?random=32",
    category: "cities",
  },
  {
    id: "13",
    cityName: "Hong Kong",
    countryName: "China",
    image: "https://picsum.photos/300/200?random=33",
    category: "cities",
  },
  {
    id: "14",
    cityName: "Barcelona",
    countryName: "Spain",
    image: "https://picsum.photos/300/200?random=34",
    category: "cities",
  },
  {
    id: "15",
    cityName: "Amsterdam",
    countryName: "Netherlands",
    image: "https://picsum.photos/300/200?random=35",
    category: "cities",
  },
  {
    id: "16",
    cityName: "Rome",
    countryName: "Italy",
    image: "https://picsum.photos/300/200?random=36",
    category: "cities",
  },
  {
    id: "17",
    cityName: "Berlin",
    countryName: "Germany",
    image: "https://picsum.photos/300/200?random=37",
    category: "cities",
  },
  {
    id: "18",
    cityName: "Vienna",
    countryName: "Austria",
    image: "https://picsum.photos/300/200?random=38",
    category: "cities",
  },
  // Countries
  {
    id: "19",
    cityName: "United States",
    countryName: "North America",
    image: "https://picsum.photos/300/200?random=39",
    category: "countries",
  },
  {
    id: "20",
    cityName: "United Kingdom",
    countryName: "Europe",
    image: "https://picsum.photos/300/200?random=40",
    category: "countries",
  },
  {
    id: "21",
    cityName: "France",
    countryName: "Europe",
    image: "https://picsum.photos/300/200?random=41",
    category: "countries",
  },
  {
    id: "22",
    cityName: "Germany",
    countryName: "Europe",
    image: "https://picsum.photos/300/200?random=42",
    category: "countries",
  },
  {
    id: "23",
    cityName: "Italy",
    countryName: "Europe",
    image: "https://picsum.photos/300/200?random=43",
    category: "countries",
  },
  {
    id: "24",
    cityName: "Spain",
    countryName: "Europe",
    image: "https://picsum.photos/300/200?random=44",
    category: "countries",
  },
  {
    id: "25",
    cityName: "Japan",
    countryName: "Asia",
    image: "https://picsum.photos/300/200?random=45",
    category: "countries",
  },
  {
    id: "26",
    cityName: "Australia",
    countryName: "Oceania",
    image: "https://picsum.photos/300/200?random=46",
    category: "countries",
  },
  {
    id: "27",
    cityName: "Canada",
    countryName: "North America",
    image: "https://picsum.photos/300/200?random=47",
    category: "countries",
  },
  // Regions
  {
    id: "28",
    cityName: "Southeast Asia",
    countryName: "Asia Pacific",
    image: "https://picsum.photos/300/200?random=48",
    category: "regions",
  },
  {
    id: "29",
    cityName: "Mediterranean",
    countryName: "Europe",
    image: "https://picsum.photos/300/200?random=49",
    category: "regions",
  },
  {
    id: "30",
    cityName: "Caribbean",
    countryName: "Americas",
    image: "https://picsum.photos/300/200?random=50",
    category: "regions",
  },
  {
    id: "31",
    cityName: "Scandinavia",
    countryName: "Northern Europe",
    image: "https://picsum.photos/300/200?random=51",
    category: "regions",
  },
  {
    id: "32",
    cityName: "Middle East",
    countryName: "Asia",
    image: "https://picsum.photos/300/200?random=52",
    category: "regions",
  },
  {
    id: "33",
    cityName: "Pacific Islands",
    countryName: "Oceania",
    image: "https://picsum.photos/300/200?random=53",
    category: "regions",
  },
  {
    id: "34",
    cityName: "Eastern Europe",
    countryName: "Europe",
    image: "https://picsum.photos/300/200?random=54",
    category: "regions",
  },
  {
    id: "35",
    cityName: "South America",
    countryName: "Americas",
    image: "https://picsum.photos/300/200?random=55",
    category: "regions",
  },
  {
    id: "36",
    cityName: "Central Asia",
    countryName: "Asia",
    image: "https://picsum.photos/300/200?random=56",
    category: "regions",
  },
  // Airports
  {
    id: "37",
    cityName: "JFK Airport",
    countryName: "New York, USA",
    image: "https://picsum.photos/300/200?random=57",
    category: "airports",
  },
  {
    id: "38",
    cityName: "Heathrow Airport",
    countryName: "London, UK",
    image: "https://picsum.photos/300/200?random=58",
    category: "airports",
  },
  {
    id: "39",
    cityName: "Dubai International",
    countryName: "Dubai, UAE",
    image: "https://picsum.photos/300/200?random=59",
    category: "airports",
  },
  {
    id: "40",
    cityName: "LAX Airport",
    countryName: "Los Angeles, USA",
    image: "https://picsum.photos/300/200?random=60",
    category: "airports",
  },
  {
    id: "41",
    cityName: "Charles de Gaulle",
    countryName: "Paris, France",
    image: "https://picsum.photos/300/200?random=61",
    category: "airports",
  },
  {
    id: "42",
    cityName: "Frankfurt Airport",
    countryName: "Frankfurt, Germany",
    image: "https://picsum.photos/300/200?random=62",
    category: "airports",
  },
  {
    id: "43",
    cityName: "Changi Airport",
    countryName: "Singapore",
    image: "https://picsum.photos/300/200?random=63",
    category: "airports",
  },
  {
    id: "44",
    cityName: "Narita Airport",
    countryName: "Tokyo, Japan",
    image: "https://picsum.photos/300/200?random=64",
    category: "airports",
  },
  {
    id: "45",
    cityName: "Sydney Airport",
    countryName: "Sydney, Australia",
    image: "https://picsum.photos/300/200?random=65",
    category: "airports",
  },
];
