// @ts-nocheck
const citizenshipOptions = [
  { value: "us", label: "United States" },
  { value: "uk", label: "United Kingdom" },
  { value: "ca", label: "Canada" },
  { value: "au", label: "Australia" },
  { value: "de", label: "Germany" },
  { value: "fr", label: "France" },
  { value: "in", label: "India" },
  { value: "cn", label: "China" },
  { value: "jp", label: "Japan" },
  { value: "br", label: "Brazil" },
  { value: "mx", label: "Mexico" },
  { value: "it", label: "Italy" },
  { value: "es", label: "Spain" },
  { value: "nl", label: "Netherlands" },
  { value: "ch", label: "Switzerland" },
  { value: "se", label: "Sweden" },
  { value: "no", label: "Norway" },
  { value: "dk", label: "Denmark" },
  { value: "fi", label: "Finland" },
  { value: "be", label: "Belgium" },
  { value: "at", label: "Austria" },
  { value: "ie", label: "Ireland" },
  { value: "nz", label: "New Zealand" },
  { value: "sg", label: "Singapore" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "sa", label: "Saudi Arabia" },
  { value: "kr", label: "South Korea" },
  { value: "th", label: "Thailand" },
  { value: "my", label: "Malaysia" },
  { value: "ph", label: "Philippines" },
  { value: "id", label: "Indonesia" },
  { value: "vn", label: "Vietnam" },
  { value: "za", label: "South Africa" },
  { value: "eg", label: "Egypt" },
  { value: "ng", label: "Nigeria" },
  { value: "ar", label: "Argentina" },
  { value: "cl", label: "Chile" },
  { value: "co", label: "Colombia" },
  { value: "pe", label: "Peru" },
  { value: "tr", label: "Turkey" },
  { value: "ru", label: "Russia" },
  { value: "pl", label: "Poland" },
  { value: "cz", label: "Czech Republic" },
  { value: "hu", label: "Hungary" },
  { value: "gr", label: "Greece" },
  { value: "pt", label: "Portugal" },
  { value: "il", label: "Israel" },
  { value: "other", label: "Other" },
];

export default citizenshipOptions;
